name: sevyhub
description: "Web 3D Printing Tool Hub"

publish_to: 'none' 

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  go_router: ^16.2.4
  provider: ^6.1.1
  flutter_svg: ^2.2.1
  image: ^4.2.0
  three_js: ^0.2.4
  three_js_controls: ^0.2.0
  three_js_helpers: ^0.2.2
  three_js_transform_controls: ^0.2.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  auto_animated: ^3.2.0
  firebase_auth: ^6.1.0
  particles_network: ^1.8.0
  file_picker: ^10.3.3
  cloud_firestore: ^6.0.3
  web: ^1.1.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/logo_color.svg
    - assets/images/svg/logo_google.svg
    - assets/examples/benchy.stl
    - assets/examples/stackabletray.stl
    - assets/examples/dragon.stl
    - assets/examples/skull.stl
    - assets/examples/mask.stl
    - assets/examples/clips.stl
    - assets/examples/hair.stl
    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 500
        - asset: assets/fonts/montserrat_semibold.ttf
          weight: 600
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700  
        - asset: assets/fonts/montserrat_italic.ttf
          style: italic
